export const controls = [
  {
    id: "adadcecefadfaf",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Not implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "adhaiphydaufhe21313",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "kajopfahfuoabfu3452",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
  {
    id: "afpiguo32452350",
    name: "Levin",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    mappedControls: ["HIPAA", "SOC 2 II", "ISO 27001"],
    status: "Partially implemented",
    createdAt: "10/2/2024",
    updatedAt: "9/10/2024",
  },
  {
    id: "asjfpsaifn9174",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Not implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "daijdiqn2h454546",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "sajdfap9074314",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
  {
    id: "vckmlkfdahkfuheu3",
    name: "Levin",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    mappedControls: ["HIPAA", "SOC 2 II", "ISO 27001"],
    status: "Partially implemented",
    createdAt: "10/2/2024",
    updatedAt: "9/10/2024",
  },
  {
    id: "sdakfnlaifoaifa",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Partially implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "adsjajfoauhngjk",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "afskpfjpfiauhegouba",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
  {
    id: "adaksfpoajaoihgunv",
    name: "Levin",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    mappedControls: ["HIPAA", "SOC 2 II", "ISO 27001"],
    status: "Partially implemented",
    createdAt: "10/2/2024",
    updatedAt: "9/10/2024",
  },
  {
    id: "sdjfoaihfoudnkjdnkzfz",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Partially implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "dlaidjoau983yhu",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "aodsjdinfigiuydg",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
  {
    id: "aidjaocunubvur",
    name: "Levin",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    mappedControls: ["HIPAA", "SOC 2 II", "ISO 27001"],
    status: "Partially implemented",
    createdAt: "10/2/2024",
    updatedAt: "9/10/2024",
  },
  {
    id: "ladijfoiwengkjngbds",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Not implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "aopdaosfhwibv",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "opi09u34nfiuygbd",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
  {
    id: "asfhuiobeniudbnfhb",
    name: "Levin",
    description:
      "Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.",
    mappedControls: ["HIPAA", "SOC 2 II", "ISO 27001"],
    status: "Partially implemented",
    createdAt: "10/2/2024",
    updatedAt: "9/10/2024",
  },
  {
    id: "asdjasofihaofnkjvda",
    name: "Clerissa",
    description:
      "Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "8/22/2024",
    updatedAt: "12/5/2023",
  },
  {
    id: "apfsdijiufhif",
    name: "Ollie",
    description: "Nunc purus. Phasellus in felis.",
    mappedControls: ["SOC 2 II", "HIPAA", "HIPAA"],
    status: "Fully implemented",
    createdAt: "12/21/2023",
    updatedAt: "12/13/2023",
  },
  {
    id: "apdjaofhuagg",
    name: "Wilek",
    description: "Ut tellus.",
    mappedControls: ["SOC 2 II", "PCI DSS", "ISO 27001"],
    status: "Not implemented",
    createdAt: "6/5/2024",
    updatedAt: "6/30/2024",
  },
];
