/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "cybermap": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "evidences": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "images": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "policy-templates": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "user": {
      "id": string
      "type": "sst.aws.CognitoUserPool"
    }
    "user-client": {
      "id": string
      "secret": string
      "type": "sst.aws.CognitoUserPoolClient"
    }
  }
}
