import type { IEmployee } from "../types";

export const employees: IEmployee[] = [
  {
    id: "6761ffc5fc13ae246fe1c6e8",
    firstName: "Sibyl",
    lastName: "Sommerfeld",
    employeeId: "54-7590372",
    email: "ssommerfeld0@tripadvisor.com",
    jobTitle: "Dental Hygienist",
    gender: "Bigender",
    hireDate: "4/8/2024",
    terminationDate: "6/9/2024",
    lastSeen: "10/12/2024",
    lastPasswordUpdate: "4/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6e9",
    firstName: "Gerty",
    lastName: "Brackley",
    employeeId: "66-2443180",
    email: "gbrackley1@irs.gov",
    jobTitle: "Assistant Media Planner",
    gender: "Female",
    hireDate: "2/4/2024",
    lastSeen: "12/6/2024",
    lastPasswordUpdate: "6/16/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6ea",
    firstName: "Mathe",
    lastName: "Anders",
    employeeId: "88-7112223",
    email: "manders2@t.co",
    jobTitle: "General Manager",
    gender: "Male",
    hireDate: "5/22/2024",
    lastSeen: "6/20/2024",
    lastPasswordUpdate: "6/17/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6eb",
    firstName: "Gannon",
    lastName: "Pagelsen",
    employeeId: "15-6505141",
    email: "gpagelsen3@theglobeandmail.com",
    jobTitle: "Civil Engineer",
    gender: "Male",
    hireDate: "1/1/2024",
    terminationDate: "8/3/2024",
    lastSeen: "2/12/2024",
    lastPasswordUpdate: "9/15/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6ec",
    firstName: "Hurlee",
    lastName: "Quail",
    employeeId: "06-9478700",
    email: "hquail4@acquirethisname.com",
    jobTitle: "Help Desk Technician",
    gender: "Agender",
    hireDate: "7/29/2024",
    lastSeen: "4/3/2024",
    lastPasswordUpdate: "8/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6ed",
    firstName: "Margaux",
    lastName: "Britney",
    employeeId: "34-5924248",
    email: "mbritney5@bbc.co.uk",
    jobTitle: "Librarian",
    gender: "Female",
    hireDate: "6/23/2024",
    lastSeen: "9/30/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6ee",
    firstName: "Sonnie",
    lastName: "Gocke",
    employeeId: "00-4249685",
    email: "sgocke6@dmoz.org",
    jobTitle: "Media Manager I",
    gender: "Bigender",
    hireDate: "4/5/2024",
    terminationDate: "5/2/2024",
    lastSeen: "10/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6ef",
    firstName: "Broderick",
    lastName: "Elam",
    employeeId: "05-1201538",
    email: "belam7@rediff.com",
    jobTitle: "Executive Secretary",
    gender: "Male",
    hireDate: "4/9/2024",
    lastSeen: "10/23/2024",
    lastPasswordUpdate: "11/19/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6f0",
    firstName: "Blair",
    lastName: "Sidney",
    employeeId: "85-6203740",
    email: "bsidney8@hexun.com",
    jobTitle: "Engineer II",
    gender: "Male",
    hireDate: "9/16/2024",
    lastSeen: "3/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "6761ffc5fc13ae246fe1c6f1",
    firstName: "Nels",
    lastName: "Widdicombe",
    employeeId: "80-0994327",
    email: "nwiddicombe9@addthis.com",
    jobTitle: "Quality Engineer",
    gender: "Male",
    hireDate: "4/30/2024",
    terminationDate: "7/22/2024",
    lastSeen: "9/30/2024",
    lastPasswordUpdate: "10/2/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
];
