export const employees = [
  {
    id: "51-2480829",
    firstName: "Meggy",
    lastName: "Rutley",
    email: "mrutley0@surveymonkey.com",
    gender: "Female",
    hireDate: "9/30/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "36-7437986",
    firstName: "Sven",
    lastName: "Speares",
    email: "sspeares1@unc.edu",
    gender: "Male",
    hireDate: "12/27/2023",
    terminationDate: "5/2/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-2795295",
    firstName: "Emlyn",
    lastName: "Offin",
    email: "eoffin2@bbc.co.uk",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "68-2701752",
    firstName: "Chloris",
    lastName: "Carruth",
    email: "ccarruth3@opensource.org",
    gender: "Female",
    hireDate: "1/15/2024",
    terminationDate: "6/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "69-2713738",
    firstName: "Garold",
    lastName: "St Ledger",
    email: "gstledger4@squarespace.com",
    gender: "Non-binary",
    hireDate: "12/9/2023",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "78-6378998",
    firstName: "Lynnette",
    lastName: "Binnes",
    email: "lbinnes5@blogger.com",
    gender: "Female",
    hireDate: "2/4/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "84-0960821",
    firstName: "Louis",
    lastName: "Jaggar",
    email: "ljaggar6@marketwatch.com",
    gender: "Non-binary",
    hireDate: "1/25/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "76-8167082",
    firstName: "Morgan",
    lastName: "Domenico",
    email: "mdomenico7@diigo.com",
    gender: "Male",
    hireDate: "2/1/2024",
    terminationDate: "7/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "33-1882337",
    firstName: "Malissia",
    lastName: "Gail",
    email: "mgail8@cnbc.com",
    gender: "Female",
    hireDate: "7/24/2024",
    terminationDate: "1/28/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
];
