export const employees = [
  {
    id: "51-2480829",
    firstName: "Meggy",
    lastName: "Rutley",
    email: "mrutley0@surveymonkey.com",
    gender: "Female",
    hireDate: "9/30/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "36-7437986",
    firstName: "Sven",
    lastName: "Speares",
    email: "sspeares1@unc.edu",
    gender: "Male",
    hireDate: "12/27/2023",
    terminationDate: "5/2/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-2795295",
    firstName: "Emlyn",
    lastName: "Offin",
    email: "eoffin2@bbc.co.uk",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "68-2701752",
    firstName: "Chloris",
    lastName: "Carruth",
    email: "ccarruth3@opensource.org",
    gender: "Female",
    hireDate: "1/15/2024",
    terminationDate: "6/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "69-2713738",
    firstName: "Garold",
    lastName: "St Ledger",
    email: "gstledger4@squarespace.com",
    gender: "Non-binary",
    hireDate: "12/9/2023",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "78-6378998",
    firstName: "Lynnette",
    lastName: "Binnes",
    email: "lbinnes5@blogger.com",
    gender: "Female",
    hireDate: "2/4/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "84-0960821",
    firstName: "Louis",
    lastName: "Jaggar",
    email: "ljaggar6@marketwatch.com",
    gender: "Non-binary",
    hireDate: "1/25/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": false },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "76-8167082",
    firstName: "Morgan",
    lastName: "Domenico",
    email: "mdomenico7@diigo.com",
    gender: "Male",
    hireDate: "2/1/2024",
    terminationDate: "7/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "33-1882337",
    firstName: "Malissia",
    lastName: "Gail",
    email: "mgail8@cnbc.com",
    gender: "Female",
    hireDate: "7/24/2024",
    terminationDate: "1/28/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "18-8153611",
    firstName: "Hillel",
    lastName: "Theodoris",
    email: "htheodoris9@posterous.com",
    gender: "Male",
    hireDate: "6/3/2024",
    terminationDate: "7/3/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "80-8349385",
    firstName: "Jacquette",
    lastName: "Ramage",
    email: "jramagea@discovery.com",
    gender: "Female",
    hireDate: "9/21/2024",
    terminationDate: "1/27/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": true },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": true },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "74-5736757",
    firstName: "Alexander",
    lastName: "Zoppie",
    email: "azoppieb@un.org",
    gender: "Male",
    hireDate: "4/26/2024",
    terminationDate: "11/29/2023",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": false },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": true },
    ],
  },
  {
    id: "65-6733213",
    firstName: "Riki",
    lastName: "Heakins",
    email: "rheakinsc@i2i.jp",
    gender: "Female",
    hireDate: "2/6/2024",
    terminationDate: "1/11/2024",
    complianceList: [
      { "Policy Acknowledgement": true },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": true },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
  {
    id: "10-0320300",
    firstName: "York",
    lastName: "Ramsell",
    email: "yramselld@yahoo.co.jp",
    gender: "Male",
    hireDate: "6/9/2024",
    terminationDate: "4/9/2024",
    complianceList: [
      { "Policy Acknowledgement": false },
      { "Identity MFA": true },
      { "Background Check": false },
      { "Security Training": false },
      { "Device Compliance": true },
      { "Password Managers": false },
      { "Anti-Virus": true },
      { "Auto-Updates": false },
    ],
  },
];

[
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6e8" },
    firstName: "Sibyl",
    lastName: "Sommerfeld",
    employeeId: "54-7590372",
    email: "ssommerfeld0@tripadvisor.com",
    jobTitle: "Dental Hygienist",
    gender: "Bigender",
    hireDate: "4/8/2024",
    terminationDate: "6/9/2024",
    lastSeen: "10/12/2024",
    lastPasswordUpdate: "4/21/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6e9" },
    firstName: "Gerty",
    lastName: "Brackley",
    employeeId: "66-2443180",
    email: "gbrackley1@irs.gov",
    jobTitle: "Assistant Media Planner",
    gender: "Female",
    hireDate: "2/4/2024",
    terminationDate: "5/6/2024",
    lastSeen: "12/6/2024",
    lastPasswordUpdate: "6/16/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6ea" },
    firstName: "Mathe",
    lastName: "Anders",
    employeeId: "88-7112223",
    email: "manders2@t.co",
    jobTitle: "General Manager",
    gender: "Male",
    hireDate: "5/22/2024",
    terminationDate: "9/17/2024",
    lastSeen: "6/20/2024",
    lastPasswordUpdate: "6/17/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6eb" },
    firstName: "Gannon",
    lastName: "Pagelsen",
    employeeId: "15-6505141",
    email: "gpagelsen3@theglobeandmail.com",
    jobTitle: "Civil Engineer",
    gender: "Male",
    hireDate: "1/1/2024",
    terminationDate: "8/3/2024",
    lastSeen: "2/12/2024",
    lastPasswordUpdate: "9/15/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6ec" },
    firstName: "Hurlee",
    lastName: "Quail",
    employeeId: "06-9478700",
    email: "hquail4@acquirethisname.com",
    jobTitle: "Help Desk Technician",
    gender: "Agender",
    hireDate: "7/29/2024",
    terminationDate: "7/8/2024",
    lastSeen: "4/3/2024",
    lastPasswordUpdate: "8/21/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6ed" },
    firstName: "Margaux",
    lastName: "Britney",
    employeeId: "34-5924248",
    email: "mbritney5@bbc.co.uk",
    jobTitle: "Librarian",
    gender: "Female",
    hireDate: "6/23/2024",
    terminationDate: "3/7/2024",
    lastSeen: "9/30/2024",
    lastPasswordUpdate: "8/17/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6ee" },
    firstName: "Sonnie",
    lastName: "Gocke",
    employeeId: "00-4249685",
    email: "sgocke6@dmoz.org",
    jobTitle: "Media Manager I",
    gender: "Bigender",
    hireDate: "4/5/2024",
    terminationDate: "5/2/2024",
    lastSeen: "10/3/2024",
    lastPasswordUpdate: "12/16/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6ef" },
    firstName: "Broderick",
    lastName: "Elam",
    employeeId: "05-1201538",
    email: "belam7@rediff.com",
    jobTitle: "Executive Secretary",
    gender: "Male",
    hireDate: "4/9/2024",
    terminationDate: "5/23/2024",
    lastSeen: "10/23/2024",
    lastPasswordUpdate: "11/19/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6f0" },
    firstName: "Blair",
    lastName: "Sidney",
    employeeId: "85-6203740",
    email: "bsidney8@hexun.com",
    jobTitle: "Engineer II",
    gender: "Male",
    hireDate: "9/16/2024",
    terminationDate: "8/24/2024",
    lastSeen: "3/11/2024",
    lastPasswordUpdate: "10/9/2024",
  },
  {
    id: { $oid: "6761ffc5fc13ae246fe1c6f1" },
    firstName: "Nels",
    lastName: "Widdicombe",
    employeeId: "80-0994327",
    email: "nwiddicombe9@addthis.com",
    jobTitle: "Quality Engineer",
    gender: "Male",
    hireDate: "4/30/2024",
    terminationDate: "7/22/2024",
    lastSeen: "9/30/2024",
    lastPasswordUpdate: "10/2/2024",
  },
];
